# Generated by Django 2.0.3 on 2018-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20180406_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_money',
            field=models.IntegerField(default=0),
        ),
    ]
