# Generated by Django 2.0.3 on 2018-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_event_available_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
