# Generated by Django 2.0.3 on 2018-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20180407_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='01-01-2020T12:00:00Z', verbose_name='date published'),
        ),
    ]
