# Generated by Django 2.0.3 on 2018-04-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20180409_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
