# Generated by Django 2.0.3 on 2018-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20180409_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='reservation',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
