# Generated by Django 2.0.3 on 2018-04-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20180409_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreservation',
            old_name='reservation',
            new_name='user',
        ),
    ]
