# Generated by Django 2.0.3 on 2018-04-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20180419_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Event'),
        ),
    ]
