# Generated by Django 2.0.3 on 2018-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_auto_20180419_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='event',
            field=models.CharField(default='event', max_length=200),
        ),
    ]
