# Generated by Django 2.0.3 on 2018-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_auto_20180420_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff_ticket_price',
            field=models.IntegerField(default=0),
        ),
    ]
