# Generated by Django 2.0.3 on 2018-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_event_staff_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
