# Generated by Django 2.0.3 on 2018-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_eventreservation_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='address', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='cap',
            field=models.CharField(default='cap', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='city', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='nation',
            field=models.CharField(default='nation', max_length=200),
        ),
    ]
