# Generated by Django 2.0.3 on 2018-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_auto_20180430_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('document', models.FileField(upload_to='reservations/static/documents')),
                ('reservation', models.CharField(default='reservation', max_length=200)),
            ],
        ),
    ]
