# Generated by Django 2.0.3 on 2018-05-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='event',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventreservation',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
