# Generated by Django 2.0.3 on 2018-05-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_auto_20180501_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contDeadline',
            field=models.CharField(default='contDeadline', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='subsDeadline',
            field=models.CharField(default='subsDeadline', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='subsStart',
            field=models.CharField(default='subsStart', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
