# Generated by Django 2.0.3 on 2018-05-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_auto_20180502_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_open_contr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
