# Generated by Django 2.0.3 on 2018-05-02 19:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0029_auto_20180502_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dates',
            field=jsonfield.fields.JSONField(),
        ),
    ]
