# Generated by Django 2.0.3 on 2018-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0030_auto_20180502_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff_ticket_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
    ]
