# Generated by Django 2.0.3 on 2018-05-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0031_auto_20180503_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='contDeadline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='subsDeadline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='subsStart',
            field=models.CharField(default='', max_length=200),
        ),
    ]
