# Generated by Django 2.0.3 on 2018-05-03 16:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0032_auto_20180503_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dates',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
