# Generated by Django 2.0.3 on 2018-05-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0033_auto_20180503_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contDeadline',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subsDeadline',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subsStart',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
