# Generated by Django 2.0.3 on 2018-05-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0035_auto_20180504_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservation',
            name='bank_user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
