# Generated by Django 2.0.3 on 2018-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0036_eventreservation_bank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_money',
            field=models.FloatField(default=0),
        ),
    ]
