# Generated by Django 2.0.3 on 2018-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0042_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='crowd_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='templates/reservations/reservations/images/'),
        ),
    ]
