# Generated by Django 2.0.3 on 2018-11-30 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0058_auto_20181129_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likoin_address', models.CharField(default='', max_length=255)),
                ('buck_address', models.CharField(default='', max_length=255)),
                ('crowdsale_address', models.CharField(default='', max_length=255)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
