# Generated by Django 2.0.3 on 2018-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0060_auto_20181201_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistcontracts',
            name='artifactsManager_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artistcontracts',
            name='voting_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
